name       : bluedevil
version    : 5.20.5
release    : 60
source     :
    - https://cdn.download.kde.org/stable/plasma/5.20.5/bluedevil-5.20.5.tar.xz : b3de4e903c5669a63688940513ab7035b90d5950635c824857ad8d6a9adbeb2e
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Bluetooth stack for KDE Plasma
description: |
    Bluedevil is a project which intends to integrate the Bluetooth technology within KDE workspace and applications.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - bluez-qt-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kded-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
