name       : bluedevil
version    : 5.24.4
release    : 78
source     :
    - https://cdn.download.kde.org/stable/plasma/5.24.4/bluedevil-5.24.4.tar.xz : 83778e9cd952c6efeb786395d3fb9f5d4e6aa65d2ef2bc02ad7d256a3201f0d6
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Bluetooth stack for KDE Plasma
description: |
    Bluedevil is a project which intends to integrate the Bluetooth technology within KDE workspace and applications.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - bluez-qt-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kded-devel
    - kio-devel
    - kirigami2-devel
    - knotifications-devel
    - plasma-framework-devel
rundeps    :
    - kirigami2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
