name       : bluedevil
version    : 5.15.3
release    : 31
source     :
    - https://cdn.download.kde.org/stable/plasma/5.15.3/bluedevil-5.15.3.tar.xz : 40edc97e2236655114ef0fe77fa357c70fcf07c555fbe1b40d45f2dc7c90b1ed
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Bluetooth stack for KDE Plasma
description: |
    Bluedevil is a project which intends to integrate the Bluetooth technology within KDE workspace and applications.
builddeps  :
    - pkgconfig(Qt5Qml)
    - bluez-qt-devel
    - extra-cmake-modules
    - kdbusaddons-devel
    - kded-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwidgetsaddons-devel
    - plasma-framework-devel
    - shared-mime-info
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
