name       : bluedevil
version    : 5.11.5
release    : 10
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.5/bluedevil-5.11.5.tar.xz : 059a2372839c8687ebfbf6268dc28847000ec5993f6528ecbed40a977170ed77
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Bluetooth stack for KDE Plasma
description: |
    Bluedevil is a project which intends to integrate the Bluetooth technology within KDE workspace and applications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - bluez-qt-devel
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kded-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - plasma-framework-devel
    - shared-mime-info
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
