name       : bluedevil
version    : 5.19.3
release    : 51
source     :
    - https://cdn.download.kde.org/stable/plasma/5.19.3/bluedevil-5.19.3.tar.xz : e9ddb2734807ef239e562399a6d9cbebf841da3f39d930f892e79e568976ed74
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Bluetooth stack for KDE Plasma
description: |
    Bluedevil is a project which intends to integrate the Bluetooth technology within KDE workspace and applications.
builddeps  :
    - pkgconfig(Qt5Qml)
    - bluez-qt-devel
    - extra-cmake-modules
    - kdbusaddons-devel
    - kded-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwidgetsaddons-devel
    - plasma-framework-devel
    - shared-mime-info
setup      : |
    %patch -p1 < $pkgfiles/placeholder.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
