name       : bluedevil
version    : 5.13.2
release    : 19
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.2/bluedevil-5.13.2.tar.xz : 0731823bae6620a1211e43d78b8c615508bc360313e41ba50fad68807d15379a
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Bluetooth stack for KDE Plasma
description: |
    Bluedevil is a project which intends to integrate the Bluetooth technology within KDE workspace and applications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - bluez-qt-devel
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kded-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - plasma-framework-devel
    - shared-mime-info
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
