name       : bluedevil
version    : 5.25.3
release    : 81
source     :
    - https://cdn.download.kde.org/stable/plasma/5.25.3/bluedevil-5.25.3.tar.xz : 656173f9d18ce153dc5b3638006d0eefa809e57c4c66aad1a118d1d272a93615
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Bluetooth stack for KDE Plasma
description: |
    Bluedevil is a project which intends to integrate the Bluetooth technology within KDE workspace and applications.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - bluez-qt-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kded-devel
    - kio-devel
    - kirigami2-devel
    - knotifications-devel
    - plasma-framework-devel
rundeps    :
    - kirigami2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
