name       : bluedevil
version    : 5.11.1
release    : 6
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.1/bluedevil-5.11.1.tar.xz : 58a0a4bfbd99ef4535b7ee6380dc3a53644f367932205b8694f9bc7ed01d3e5c
license    : GPL-2.0
component  : desktop.kde.core
summary    : Bluetooth stack for KDE Plasma
description: |
    Bluedevil is a project which intends to integrate the Bluetooth technology within KDE workspace and applications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - bluez-qt-devel
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kded-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - plasma-framework-devel
    - shared-mime-info
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
