name       : bluedevil
version    : 5.10.3
release    : 3
source     :
    - https://download.kde.org/stable/plasma/5.10.3/bluedevil-5.10.3.tar.xz : cf80706d6966abaa7073c73cfce1361510995f272611b979116c626e1168130f
license    : GPL-2.0
component  : desktop.kde.core
summary    : Bluetooth stack for KDE Plasma
description: |
    Bluedevil is a project which intends to integrate the Bluetooth technology within KDE workspace and applications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - bluez-qt-devel
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kded-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - plasma-framework-devel
    - shared-mime-info
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
