name       : bluedevil
version    : 5.11.2
release    : 7
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.2/bluedevil-5.11.2.tar.xz : 58ee7d182ed4c04cc6bbd7ee75bcf69d1d1ffc234816f6d86e8c0ffb91af9b3f
license    : GPL-2.0
component  : desktop.kde.core
summary    : Bluetooth stack for KDE Plasma
description: |
    Bluedevil is a project which intends to integrate the Bluetooth technology within KDE workspace and applications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - bluez-qt-devel
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kded-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - plasma-framework-devel
    - shared-mime-info
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
